item {
    id: 1
    name: 'sku_medium_brush'
}
item {
    id: 2
    name: 'sku_small_brush'
}
item {
    id: 3
    name: 'sku_scrapper'
}
item {
    id: 4
    name: 'sku_electrical_tape'
}
item {
    id: 5
    name: 'sku_glue'
}
item {
    id: 6
    name: 'sku_13a_adapter'
}
item {
    id: 7
    name: 'sku_paint_roller'
}
item {
    id: 8
    name: 'sku_sss304_hand_spray_set'
}
item {
    id: 9
    name: 'sku_gardening_tool'
}
item {
    id: 10
    name: 'sku_shower_head_s4'
}
item {
    id: 11
    name: 'sku_white_bidet_holder'
}
item {
    id: 12
    name: 'sku_ss304_bidet_head'
}
item {
    id: 13
    name: 'sku_ss304_bidet_hose'
}
item {
    id: 14
    name: 'sku_water_tap'
}